[package]
title = "{{ extension_display_name }}"
version = "{{ version }}"  # Semantic Versionning is used: https://semver.org/
description = "The setup extension for the USD Viewer template. This includes messaging functionality, also."
readme  = "docs/README.md"  # Path (relative to the root) or content of readme markdown file for UI.
repository = "https://github.com/NVIDIA-Omniverse/kit-extension-template"  # URL of the extension source repository.
category = "Setup"  # One of categories for UI.
keywords = ["kit", "app", "setup", "messaging"]  # Keywords for the extension
icon = "data/icon.png"  # Icon to show in the extension manager
preview_image = "data/preview.png"  # Preview to show in the extension manager


[dependencies]
"omni.activity.ui" = {}   # Progress activity messages
"omni.kit.livestream.messaging" = {}
"omni.kit.quicklayout" = {}
"omni.kit.viewport.utility" = {}
"omni.kit.window.title" = {}

[settings.exts."{{extension_name }}"]
menu_visible = false
viewport_splash = ""


[[python.module]]  # Main python module this extension provides, it will be publicly available as "import omni.hello.world".
name = "{{ extension_name }}"


[[test]]
args = [
    "--/app/layout/name=default",
    "--no-window",
]

# Extra dependencies only to be used during test run
dependencies = [
    # none
]


[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]
